name: Generate Changelog

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important: This ensures all history is fetched for changelog generation
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g conventional-changelog-cli@5.0.0

      - name: Generate changelog
        run: |
          # Create an empty CHANGELOG.md file if it doesn't exist
          touch CHANGELOG.md

          # Print git log to debug
          echo "Recent commits:"
          git log -n 5 --pretty=format:"%h - %s (%an)"

          # Generate the changelog with verbose output
          echo "Generating changelog..."
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0 -v

          # Show the content of the generated file (if any)
          echo "CHANGELOG.md content:"
          cat CHANGELOG.md

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "cgb37@miami.edu"
          git config --local user.name "Charles"

          # Check if there are changes to commit
          if git diff --exit-code --quiet CHANGELOG.md; then
            echo "No changes to commit"
            exit 0
          fi

          git add CHANGELOG.md
          git commit -m "docs: update changelog [skip ci]"
          git push